services:
  dremio:
    platform: linux/x86_64
    image: docker.io/dremio/dremio-oss:25.1
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
    container_name: dremio
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    depends_on:
      - minio
      - nessie
  minio:
    image: docker.io/minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=$AWS_ACCESS_KEY_ID
      - MINIO_ROOT_PASSWORD=$AWS_SECRET_ACCESS_KEY
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - ./data_example:/minio_data/raw
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address ':9001' &
      sleep 5;
      mc alias set myminio http://localhost:9000 $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY;
      mc mb myminio/raw;
      mc mb myminio/metadata;
      mc cp --recursive /minio_data/raw/* myminio/raw;
      tail -f /dev/null"
    env_file: ./.env
  nessie:
    image: docker.io/projectnessie/nessie:latest
    container_name: nessie
    volumes:
      - ./nessie-data:/nessie/data
    ports:
      - 19120:19120
