#FROM python:3.10
FROM jupyter/datascience-notebook:python-3.10

#EXPOSE 8888

COPY requirements_eda.txt requirements_eda.txt

# Install requirements and change to dark theme in Jupyter Lab
RUN pip install -r requirements_eda.txt \
  && mkdir -p $HOME/.jupyter/lab/user-settings/@jupyterlab/apputils-extension \
  && echo '{"theme":"JupyterLab Dark"}' > $HOME/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings 
  #\
  #&& mkdir -p /home/notebooks && mkdir -p /home/raw_data

#USER tito

#CMD jupyter lab --allow-root --no-browser --ip 0.0.0.0 --notebook-dir /home/notebooks
